apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-demo-deployment
  namespace: genai-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: genai-demo
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xms1g -Xmx1g -XX:+UseG1GC -XX:+UseContainerSupport"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
            ephemeral-storage: 2Gi