apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genai-demo

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: genai-demo
  newTag: production

commonLabels:
  environment: production
  
commonAnnotations:
  environment: production
  managed-by: kustomize