apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-demo-app
  namespace: genai-demo
  labels:
    app: genai-demo
    app.kubernetes.io/name: genai-demo
    app.kubernetes.io/component: service-account
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/genai-demo-ENVIRONMENT-app-service-account-role"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/genai-demo-ENVIRONMENT-alb-controller-role"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/component: autoscaler
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/genai-demo-ENVIRONMENT-cluster-autoscaler-role"
automountServiceAccountToken: true