# Test Profile Configuration
# This configuration is active when running tests

spring:
  # Main Configuration
  main:
    lazy-initialization: true

  # Database Configuration for Tests
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # H2 Console Configuration
  h2:
    console:
      enabled: false

  # JPA Configuration for Tests
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  # Flyway Configuration for Tests
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: false

  # Test-specific configurations
  test:
    database:
      replace: none
  
  # Kafka Configuration (Completely Disabled in Tests)
  kafka:
    enabled: false  # Explicitly disable Kafka auto-configuration

# Logging Configuration for Tests
logging:
  level:
    root: WARN
    solid.humank.genaidemo: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.flywaydb: WARN
    com.zaxxer.hikari: WARN

# Management Configuration for Tests
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
  metrics:
    enable:
      all: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Profile Configuration for Tests
app:
  profile:
    name: test
    description: "Test environment configuration with H2 in-memory database"
    features:
      h2-console: true
      debug-logging: false
      in-memory-events: true
      kafka-events: false

# Disable tracing in tests
tracing:
  enabled: false
  sampling:
    ratio: 0.0

# Test environment observability configuration
genai-demo:
  events:
    publisher: in-memory  # 測試環境使用記憶體事件處理
    async: false         # 同步處理便於測試
  observability:
    enabled: true        # 啟用可觀測性以便測試
    analytics:
      enabled: true
      storage: in-memory  # 測試環境使用記憶體儲存
      retention-minutes: 5  # 短期保留便於測試
      batch-processing:
        enabled: false    # 測試環境不需要批次處理
    tracing:
      enabled: false      # 測試環境關閉追蹤以提高效能
      sampling-rate: 0.0
    metrics:
      enabled: true
      export-interval: 1s  # 快速匯出便於測試驗證
      business-metrics:
        enabled: true
        retention-hours: 1
      performance-metrics:
        enabled: false     # 測試環境不需要效能指標
    logging:
      structured: false   # 測試環境使用簡單日誌格式
      correlation-enabled: true
      mdc-integration: true
    websocket:
      enabled: false      # 測試環境不需要 WebSocket
    distributed-tracing: false