# OpenAPI Profile Configuration
# This profile provides OpenAPI/Swagger documentation configuration
# Included by all other profiles for API documentation

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: GenAI Demo API
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    filter: false
    show-extensions: true
    show-common-extensions: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
  group-configs:
    - group: 'public-api'
      display-name: 'Public API'
      paths-to-match: '/api/**'
    - group: 'management'
      display-name: 'Management API'
      paths-to-match: '/actuator/**'

# OpenAPI Documentation Information
openapi:
  info:
    title: GenAI Demo API
    description: |
      GenAI Demo Application API Documentation
      
      This API provides comprehensive e-commerce functionality including:
      - Customer Management
      - Product Catalog
      - Order Processing
      - Payment Processing
      - Inventory Management
      - Promotion Management
      
      Built with Domain-Driven Design (DDD) and Hexagonal Architecture principles.
    version: 2.0.0
    contact:
      name: GenAI Demo Team
      email: support@genaidemo.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
  servers:
    - url: http://localhost:8080
      description: Development Server
    - url: https://api.genaidemo.com
      description: Production Server
  external-docs:
    description: Project Documentation
    url: https://github.com/genai-demo/docs

# OpenAPI Profile - No profile validation needed
# This profile only provides OpenAPI/Swagger configuration
# Profile validation is handled by the main profiles (dev, production, test)